= Можно играть в компьютер

:hp-alt-title: you can play computer
:hp-tags: life
:published_at: 2015-12-13


В детстве у моего брата было плохое зрение. Из-за этого мы очень часто ходили к окулисту. Мы это — мама, брат, я. Мы ходили достаточно часто, поэтому даже были знакомы с окулистом ну точнее мама знакома.

Меня всегда брали с собой и проверяли зрение и мне, — так сказать, заодно. Я всегда гордился своими здоровыми глазами. Ну представьте: сначала врач-окулист проверяет зрение брату, и со вздохами говорит цифру маме — «минус пять». Мама вздыхает, переживает, ведь старшему сыну всего десять лет, а уже такая тенденция, они долго обсуждают будущие очки, капли, гимнастику для глаз, таблетки, что нужно меньше читать, смотреть телевизор, смотреть в компьютер, ну и вообще меньше куда-либо смотреть. В процессе обсудят все и вся, и царя, и Ельцина, и власть, и цены на таблетки. И пару раз пройдутся по рецепту сначала вниз, а затем вверх. Ведь понять что-то в почерке врача почти не возможно.

А затем говорят, — «Ну давайте и младшего посмотрим». И еще обязательно добавят — «Они так похожи», а мама скажет, что не всем, — «Что у младшего зрение хорошее, что он в маму пошёл». Я быстро садился и мгновенно произносил: Н К И Б М Ш И Б. Я до сих пор наизусть помню эту строчку.

Дальше я спрыгивал со стула и шел в обратную сторону под слова окулиста — «единичка». Дальше мы шли домой, слушая будущие запреты и новые изменения в нашей жизни. После каждого такого похода время проводимое перед компьютером и телевизором уменьшалось. Ежедневно пились таблетки — «черника-форте». Хоть мое зрение не падало, я все равно делал это заодно. Возможно, мне были какие-то поблажки, может быть я просто забыл. Но обычно запрет применялся к обоим, и не важно кто виноват. Виноваты всегда двое.

Так происходило много лет, наверное, лет пять. Пока моё уникальное преимущество не стало пропадать. Тут я уже вышел на арену, окруженную вздохами и фразами — «Ослепнешь совсем».

После какого-то длинного перерыва моё зрение ухудшилось на единичку на одном глазу и на половинку на втором. И это был удар ниже пояса. Мне казалось, что мир не справедлив. Я получил, как мне казалось гораздо большую порцию запретов. Это не укладывалось в моей голове — «Как так, у брата аж минус пять, а у меня всего минус один. А ему можно сидеть за компьютером, а мне нет. У него же в пять раз хуже зрение?» Но ответ был — «У него уже зрение упало, за тебя мы еще повоюем».

Война продолжилась, я получил походы на электрофорез и черные очки с дырочками. На электрофорезе меня немного било током в глаза. Видимо это как-то помогало чему-то. Спалось там чудно, так что я не особо паниковал. Но с некоторыми переменами я отказывался соглашаться.

Спустя годы мое зрение устаканилось в районе минус трёх. У ношу очки только за рулем или когда смотрю на доску. И спустя наверное пять лет я опять пошел к окулисту. Ножки тряслись.

Во-первых очень сильно изменилось оборудование — я все время смотрел в какие-то странные гаджеты. Складывалось ощущение, что к окулисту давно никто не заходил, и он решил просто испробовать всё на мне. Я обалдел уже только от проектора цифр и букв на стену(это вместо всем известной таблички), а потом меня добили всякими приборами в которых показывались картинки.

Во-вторых мое зрение не упало! А даже улучшилось! Сейчас оно −1.75 на оба глаза с небольшим астигматизмом на левом. Я так этому рад. Я рассчитывал на самые худшие варианты минус пять например. Все же я по 9 часов сижу за компьютером и глаза у меня часто устают. А тут такой подарок судьбы.

Я шел радостный как будто мне вновь можно сидеть за компьютером больше брата.