= Михаил Идов "Кофемолка"
:hp-alt-title: idov kofemolka
:hp-tags: book

Сразу после прочетения книги я записываю все мысли, которые появились в голове. Затем через некоторое время расшифровываю ее.

*О книге*

У каждой супружеской пары хотя бы раз в жизни появлялась мысль - открыть семейный бизнес. Кофемолка - роман Михаила Идова о супружеской паре, которая вместе решила открыть венское кафе. Нина и Марк живут на проценты от своего жилья, ведут интелегентный образ жизни. Нина - арт-фотограф, Марк - пишет отзывы на книги молодых авторов, оба работают не ради денег. Они не готовят, не убирают, а занимаются сугубо умственной "творческой" деятельностью. 


*Хипстеры не умею делать дела, или "а давай сейчас замутим бизнес"*

Под хистерами часто понимают творческих людей, не таких как все, уникальных, ветрянных, безалаберных, тех которые не могут заниматься не любимым делом. Такие свое рода, художники свой жизни. На работе с такими тяжело. Ты либо ремесленник, либо художник. Я бы предпочел работать с ремесленником.

*Свое дело - это тяжкий ежедневный труд - сто раз подумай - ведь это тяжелее твоей работы на какого-то*

Нина и Марк открыли кофейню для себя, для души, для друзей. Так не бывает. В бизнесе нет романтики. Бизнес - это всего лишь маржа, разница между прибылью и убытками. Нет маржи - называйте себя хобби. Ави Сосна - воплощение рынка. Он видит не людей, а способ заработать. В худшие времена "Кольшинского" Марк становится немного Ави.

*Крепкие отношения = препятствия*

Отношения Марка и Нины двигаются в такт с развитием или упадком кофейни. Они долгое время были ограждены от внешего мира, не было притока новых людей, знакомств. Сидели в квартире и упивались разговорами с друг другом. Настоящие отношения - те, которые испытанны на прочность. Нина и Марк жили в радужном мире с первого своего знакомства и даже через несколько лет их отношения были хрупки. Вранья, Карина, менеджера из соседней кафе - этого ничего не могло произойти в их уютной квартире.


*Судить других, когда сам не пробовал - можно*


Марк рецензирует книги начинающих авторов и его отзывы редко оказываются положительными. Его рецензии похожи больше на разнос, после которого молодые писатели не могут оправиться. Сам Марк не написал ни одной работы. Но это совершенно не значит, что он плохой рецензент. Человек бузесловно может быть экспертом в области, в которой он сам не работал. И даже больше - каждый человек эксперт во всех областях. Уверен, что своей работой Марк спас нескольких горе-писателей. А то что он почувствовал себя в шкуре отрецензированнаго, и то - что он честно к этму отнесся - это отличный аргумент за адекватность Марка. Оценка вашей работы - это правда, которую вы знали, но боялись сказать себе.

Оценивать работы других это хорошоий способ разиваться - за счет чьего-то опыта. Учиться на чужих ошибках, а не на своих, анализировать, наблюдать и делать выводы - это можно назвать научным методом, а можно и просто спленями - если вы забыли сделать выводы. Если не было вывода, то походу вы просто посплетничали. Для тех, кто сам пробовал - есть специальное название "практикующий эксперт".

*P.S.* В книге много англиского юмора, и почти под каждой шуткой - сноска, объясняющая ее. К концу произошел такой странный эффект, - увидев сноску, я останавливался, и начинал думать в чем же шутка. Думаю автор немного перестался со сносками. Я эмоцианально чувствовал, где автор хотел съязвить, и сноски мне не были нужны. А где не понимал шутки - долго думал и это доставляло неудобство.
