= Программирование на языке C++. Склейка строк
:hp-alt-title: cplusplus programming string concat
:hp-tags: Stepic, C++, course

Задание 

https://stepic.org/lesson/Использование-указателей-540/step/7

Вам требуется реализовать функцию конкатенации (склейки) двух C-style строк. Функция конкатенации принимает на вход две C-style строки и дописывает вторую в конец первой так, чтобы первая строка представляла из себя одну C-style строку равную конкатенации двух исходных. 

Не забудьте, что в результирующей строке должен быть только один нулевой символ — тот, что является маркером конца строки. 

Гарантируется, что в первой строке достаточно памяти (т.е. она располагается в массиве достаточной длины), чтобы разместить конкатенацию обеих строк, но не больше.

Требования к реализации: при выполнении задания вы можете определять любые вспомогательные функции, если они вам нужны. Выводить или вводить что-либо не нужно. Функцию main определять не нужно.


Решение

[source, cpp]
----
#include <iostream>
using namespace std;

unsigned strlen(const char *str)
{   
	unsigned i = 0;
	for (; *str != '\0'; str++) 
	{	
		i++;
		
	}
	
	return  i;
}

void strcat(char *to, const char *from)
{
    unsigned i = strlen(to);
	for (; *from != '\0' ; from++) 
	{	
		to[i] = from[0];
		i++;
	}
	
	to[i] = '\0';
	
}

int main() {
	
	char s[] = "Hello ";
	char s1[] = "World!";
	
	strcat(s, s1);
	
    cout << s << endl;
}
----

Сам курс https://stepic.org/course/7